# Don't touch this.
_version: 1
# The locale to use while translating chat messages.
# Default value: en_US.
locale: "en_US"
# Chances that a skeleton in the nether will be replaced with a wither skeleton archer.
# Settings are between 0 and 1, separated by difficulty level.
spawnChances:
  # Easy difficulty spawn rates.
  # Default value: 0.1, a.k.a. 1 in 10 spawns.
  # Valid values are any value between 0 and 1.
  easy: 0.1
  # Normal difficulty spawn rates.
  # Default value: 0.5, a.k.a. 1 in 2 spawns.
  # Valid values are any value between 0 and 1.
  normal: 0.5
  # Hard difficulty spawn rates.
  # Default value: 1, a.k.a. all spawns.
  # Valid values are any value between 0 and 1.
  hard: 1
# Whether withers should be allowed to fire flaming arrows regardless of whether their bow has a "flame" enchantment.
# This matches vanilla functionality.
# Defaults to false.
flamingArrows: false
# Whether armor transfers from the skeleton to the wither skeleton.
# This could lead to incredibly overpowered wither skeletons!
# Defaults to false.
transferArmor: false
# Whether wither skeletons fire tipped arrows with a decay attribute.
arrowsOfDecay:
  # If true, wither skeletons will fire tipped arrows with a decay attribute.
  # Defaults to true.
  enabled: true
  # The duration in ticks that the decay will last.
  duration:
    # Easy difficulty wither effect duration in ticks..
    # Defaults to 0.
    # Valid values are whole numbers 0 or greater. Setting to 0 will cause the effect not to be applied.
    easy: 0
    # Normal difficulty wither effect duration in ticks.
    # Defaults to 200, or ten seconds.
    # Valid values are whole numbers 0 or greater. Setting to 0 will cause the effect not to be applied.
    normal: 200
    # Hard difficulty wither effect duration in ticks.
    # Defaults to 100, or five seconds.
    # Valid values are whole numbers 0 or greater. Setting to 0 will cause the effect not to be applied.
    hard: 100
  # The level of the wither effect applied to the arrows.
  effectLevel:
    # Easy difficulty arrow effect level.
    # Defaults to -1.
    # Valid values are whole numbers from -1 to 255. When set to -1, the effect will not be applied.
    easy: -1
    # Normal difficulty arrow effect level.
    # Defaults to 0.
    # Valid values are whole numbers from -1 to 255. When set to -1, the effect will not be applied.
    normal: 0
    # Hard difficulty arrow effect level.
    # Defaults to 1.
    # Valid values are whole numbers from -1 to 255. When set to -1, the effect will not be applied.
    hard: 1
# Whether Wither Skeleton archers should drop arrows on death.
# Set "dropArrows.enabled" to true to enable this functionality.
dropArrows:
  # Whether to drop arrows if a wither skeleton has a bow.
  # Will drop as "Uncraftable Tipped Arrow" with a wither effect if arrows of decay are enabled.
  # Defaults to true.
  enabled: true
  # Whether the arrows which are dropped should be normal or tipped with the Wither effect.
  # Wither effect levels depend on difficulty.
  # Ignored if dropArrows is not enabled, effect level is set to a negative value, or effect duration is set to 0.
  # Defaults to false, initially set to true.
  dropTippedArrows: true
# Whether to show debug output in the console.
# Defaults to false.
debug: false
# Whether to send usage telemetry. Uses bStats (https://bstats.org).
# Defaults to false.
# Only opt in to metrics if you are an adult, and are comfortable sharing non-identifying data with bStats.
# See the GitHub readme at https://github.com/satyrnidae/archers-of-decay for more info on metrics.
# You can also see what metrics are collected on the bStats metrics page here: https://bstats.org/plugin/bukkit/Archers%20of%20Decay/20029
# Please make sure you've read the bStats privacy policy at https://bstats.org/privacy-policy before enabling!
metrics: false
